### ISSUE TITLE
Language change not working

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#310] opened 2019-05-05 13:29 UTC
Description:

Sometimes when you change language some screens still show the old language.

Issue:

After testing around a bit it seems the problem being that we set current language when building activity. This needs to happen when we resume the activity to handle case's where we back to a previous activity.

**Comment by alexhauser** [comment] 2019-05-05 13:51
Hi @kalaspuffar , 

could this be a duplicate of Issue #218 ? I've looked at this a while back but couldn't reproduce it. Your input is very helpful, though. I'm going go get into this, should be a quick fix according to your description!

Best regards,
Alex

**Comment by kalaspuffar** [comment] 2019-05-06 03:39
Hi @alexhauser

You are probably right.  Looked but didn't find the issue. Know it was reported on the forums but didn't know if it had been added in the issue list. :)

Best regards
Daniel

**Comment by alexhauser** [comment] 2019-05-07 05:57
Hi @kalaspuffar ,

just as a short status report, it turns out that this is not the "quick fix" I've hoped for :)

Moving stuff to `onResume()` didn't get rid of all the weirdness. The activity titles/labels have to be treated differently, but I got that working. But sometimes, the content is still not updated correctly with the new language and I don't know why (yet). Will report back as soon as I have something viable.

Best regards,
Alex

**Comment by alexhauser** [comment] 2019-05-08 03:21
Hi @kalaspuffar ,

I think I've got that one nailed down. But I have an architectural question before I post the PR:

The language update code is something that we need in **all** of our activities and should definitely be handled in a superclass. But currently, not all of our activities inherit from `BaseActivity`. I guess this in on purpuse, since not all of them need the menu- and SQRL-realated logic.

What I did in my current local branch is to introduce another base class called `CommonBaseActivity` that extends `AppCompatActivity` and is being extended by `BaseActivity`. So our inheritance tree would look like this:
```
LoginBaseActivity ← BaseActivity ← CommonBaseActivity ← AppCompatActivity
```

Another option would be to include all the logic into `BaseActivity` and let **all** the activities inherit from it. This would save us from having to introduce another superclass, with the caveat of having some logic/resource overhead on activities that actually don't need it.

What's your take on this? 

Looking foward to your feedback,
Alex

**Comment by kalaspuffar** [comment] 2019-05-08 04:27
Hi @alexhauser 

I think having a deeper class hierarchy is perhaps not the best solution. Then again if we need another layer for some common code I think that is something we can look into. 

Maybe we should do a refactoring of the names though. We have a LoginBase that handles all the login logic. And we have the base activity that has all the common code that we didn't have a place to put that almost all activities use. Except for the activities we have in unbreakable flows.

Don't really find a good name for those are they called wizards? But I guess you know what I mean. Things you can't break or back out of like the "create a new identity" flow. And in those cases, we don't need the login logic or the menus and so on.

So maybe we should have a WizardBaseActivity that we can put the language logic in. So we can have that code in two places?

Maybe there is a better name for BaseActivity and LoginBaseActivity but I've not given them enough thought yet.

Best regards
Daniel

**Comment by alexhauser** [comment] 2019-05-08 05:24
Hi @kalaspuffar ,

thanks for your valuable input.

> I think having a deeper class hierarchy is perhaps not the best solution. Then again if we need another layer for some common code I think that is something we can look into.

That is exactly what I asked myself, too. But the more I think about it, the more it becomes clear to me that we should really have one base activity that **ALL** the activities inherit from and where we can put all the common code. I think this might be valuable not only for the language stuff, but also for possible features in the future that need a place for common code.

> Maybe we should do a refactoring of the names though.

> Maybe there is a better name for BaseActivity and LoginBaseActivity but I've not given them enough thought yet.

I agree. My first instinct was to rename `BaseActivity` to `SqrlBaseActivity` and let the new common layer be the `BaseActivity`. So it would look like this:
```
LoginBaseActivity ← SqrlBaseActivity ← BaseActivity ← AppCompatActivity
```

> So maybe we should have a WizardBaseActivity that we can put the language logic in. So we can have that code in two places?

To be honest, I would really dislike to have the same code in two different places, beacause it makes it hard to maintain. I'd prefer both other options (new inheritance layer / everything in one BaseActivity) over this one. Also, the common code does not only pertain to "wizard" activities, but also to standalone activities as the language activity for example. This would be handled nicely by a common base activity.

What do you think?

Best regards,
Alex

**Comment by alexhauser** [comment] 2019-05-09 15:58
Hi @kalaspuffar ,

I posted this PR now because I'll need to delete and recreate my fork repo afterwards. I must have messed up some merges and can't get a stable state for the other fixes/features I'm working on (e.g. handling the file intent, where I've already got a stable solution but can't post a PR because of the whacky state of my codebase). So maybe if you decide to merge this one, you can make the discussed refactorings yourself afterwards. Otherwise, just close this PR and we'll discuss how to proceed.

Best regards,
Alex

**Closed** 2019-05-22 07:43 UTC
Labels: Solved, bug, good first issue, help wanted
