### ISSUE TITLE
Bug: Save file does not work, permissions denied.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#232] opened 2018-12-29 20:01 UTC

**Comment by IvarSnaaijer** [comment] 2019-02-06 06:21
I was just trying to export with 0.13.1 and got an error (indicating diskspace)

**Comment by IvarSnaaijer** [comment] 2019-02-19 21:57
This looks like a duplicate of #209

**Comment by IvarSnaaijer** [comment] 2019-02-22 04:12
Tested in 0.13.3  fixed

**Comment by sengsational** [comment] 2019-02-27 18:47
This can be closed as it was a duplicate of #209

**Closed** 2019-02-27 20:36 UTC
Labels: bug
