### ISSUE TITLE
Cannot login to SQRL Test site listed on SQRL Forums

### ISSUE THREAD

**Issue by eeny999** [kalaspuffar/secure-quick-reliable-login#245] opened 2019-02-17 11:45 UTC
Unable to login to the following Test site which is listed on the SQRL Forums:
https://sqrl-test.herokuapp.com/

SQRL Forums page: 
https://sqrl.grc.com/threads/sqrl-test-websites.281/

Getting a couple of empty dialog boxes then the following two dialog boxes appearing (attached images below). I even tried refreshing the website's login page after the message boxes but was not logged in.

I am able to use Steve Gibson's Windows SQRL client to login but it does pop-up the "NO Identity Spoof Protection" warning first. 

It may be that the site is not fully SQRL compliant but just thought I'd let you know as this is a Test site listed on the official SQRL Forums.

I am able to use the client to login to the SQRL Forums so I don't think its a client settings issue.

Thanks
Travis
![screenshot_20190217-223153_sqrl login](https://user-images.githubusercontent.com/28769258/52912422-727a9500-3305-11e9-985e-31c7bee0ced7.jpg)
![screenshot_20190217-223205_sqrl login](https://user-images.githubusercontent.com/28769258/52912423-727a9500-3305-11e9-96df-96c62cc4478c.jpg)

**Comment by kalaspuffar** [comment] 2019-02-20 06:53
Well, this site is one of the older test sites that don't have the full implementation of SQRL available.

I was able to log in but got as you mentioned a lot of strange ask messages, all of them empty.

I'll debug this further when I get a chance. 

Also, the page does not reload so if you log in and then reload the page you will be logged in I believe.

Best regards
Daniel

**Comment by sengsational** [comment] 2019-03-01 02:13
I just tried going to this older site.  When I got to the site, I did click TIF base=10 (which may or may not have been correct).

But for me, the application keeps throwing up an empty dialog with an "OK" button.  There doesn't appear to be a way out of this loop.

**Comment by kalaspuffar** [comment] 2019-05-01 09:16
Seems this is a duplicate of the issue of ASK dialog stuck in a loop.

**Closed** 2019-05-01 09:16 UTC
Labels: duplicate, help wanted, question
