### ISSUE TITLE
Error message screens and other popup windows aren't renewed.

### ISSUE THREAD

**Issue by kalaspuffar** [kalaspuffar/secure-quick-reliable-login#249] opened 2019-02-21 21:27 UTC
If you stand on the first simplified view and then go around a bit in the advanced options and then return back.

Then you trigger an error by going to a stale site the application crashes due to missing window references.

**Comment by sengsational** [comment] 2019-03-01 02:01
I'm not sure how to recreate this.  I'm on SimplifiedActivity.  I click btnUseIdentity and log into sqrl.grc.com.  Then I click btnAdvancedFunctions and do a few things (cancel out of each).  Don't know how to begin "going to a stale site".

**Comment by kalaspuffar** [comment] 2019-03-01 05:03
Hi @sengsational

Stale site is made by opening the site and have it open for an hour or two and the nut should be too old.

Best regards
Daniel

**Comment by sengsational** [comment] 2019-03-06 21:03
I think I have a recipe to reproduce this (or a similar bug) that doesn't require waiting.  I've done this several times and it worked the same each time.  Generally the steps are 1) start the app fresh, 2) change settings, 3) attempt login on sqrl.grc.com.  I get `W/IInputConnectionWrapper: sendKeyEvent on inactive InputConnection` in Logcat.   At this point, the error has happened.  Just for completeness, I'll continue: the app then prompts for the full password (I think the error dialog is hidden).  Then, hitting enter displays the 'wrong password' dialog.  Trying to login to sqrl.grc.com again works.

1) Fresh start the app
2) Advanced Functions > Settings > (make a change, for instance change idle timeout) > Save > (type SQRL master password)
3) Scan QR code on sqrl.grc.com
4) Type first four characters of the password
5) App requests typing full password (unexpected), `...inactive InputConnection` (unexpected)

**Comment by sengsational** [comment] 2019-03-06 22:45
I'm thinking this might be a different bug.  In `SimplifiedActivity.onActivityResult()` in 'handler.postDlayed(() -> {})`, I put `storage.clearQuickPass(this)` and that got rid of the error.  Of course I had to type the entire password.

**Comment by sengsational** [comment] 2019-03-09 21:57
There must be something different happening when the quick pass stuff is getting generated from the _save settings page_ as opposed from when it's generated _after logging in on the forum site_.

I added a bunch of logging and see that it seems to be doing roughly the same thing in both cases, but there must be some some flaw in quick pass management when the full master password is entered on the _save settings page_.

**Comment by kalaspuffar** [comment] 2019-06-24 05:00
I can't reproduce this error anymore. Can we close this one for now? 

I think we should look at setting the QuickPass when saving settings but we reset QuickPass today so we will not have the mentioned error.

**Comment by alexhauser** [comment] 2019-06-24 17:26
I agree. Let's close this but keep an eye on stuff like this going forward.

**Closed** 2019-06-24 18:36 UTC
Labels: bug
